/**
 * Machine-readable failure codes.
 * Taxonomy: VALIDATION | BUSINESS | REFERENCE | CONFLICT | INFRA
 */
export enum FailureCode {
  // VALIDATION
  MISSING_IDEMPOTENCY_KEY = "MISSING_IDEMPOTENCY_KEY",
  INVALID_MONEY = "INVALID_MONEY",
  KIND_NOT_ALLOWED = "KIND_NOT_ALLOWED",
  REFERENCE_REQUIRED = "REFERENCE_REQUIRED",
  REFERENCE_NOT_ALLOWED = "REFERENCE_NOT_ALLOWED",
  VALIDATION_ERROR = "VALIDATION_ERROR",

  // BUSINESS
  INSUFFICIENT_BALANCE = "INSUFFICIENT_BALANCE",
  REFUND_WOULD_OVERDRAW = "REFUND_WOULD_OVERDRAW",
  ROLLBACK_WOULD_OVERDRAW = "ROLLBACK_WOULD_OVERDRAW",
  REFERENCE_ALREADY_REVERSED = "REFERENCE_ALREADY_REVERSED",
  REFERENCE_MISMATCH = "REFERENCE_MISMATCH",
  REFERENCE_AMOUNT_MISMATCH = "REFERENCE_AMOUNT_MISMATCH",
  REFERENCE_INVALID_KIND = "REFERENCE_INVALID_KIND",
  WALLET_CURRENCY_MISMATCH = "WALLET_CURRENCY_MISMATCH",

  // REFERENCE
  REFERENCE_NOT_FOUND = "REFERENCE_NOT_FOUND",

  // CONFLICT
  IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT",
  WALLET_ALREADY_EXISTS = "WALLET_ALREADY_EXISTS",

  // INFRA
  DEPENDENCY_UNAVAILABLE = "DEPENDENCY_UNAVAILABLE",
  LOCK_TIMEOUT = "LOCK_TIMEOUT",
}

export enum WagerTransactionKind {
  Opening = "OPENING",
  Bet = "BET",
  Win = "WIN",
  Loss = "LOSS",
  Refund = "REFUND",
  Rollback = "ROLLBACK",
}

export enum WagerTransactionStatus {
  Pending = "PENDING",
  PendingReference = "PENDING_REFERENCE",
  Processed = "PROCESSED",
  Rejected = "REJECTED",
  Failed = "FAILED",
}

export enum LedgerDirection {
  Debit = "DEBIT",
  Credit = "CREDIT",
}
